/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ca76f6f3-684e-49c2-8eb4-7d86c7ea0692",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_vRyeZ1Van",
    "aws_user_pools_web_client_id": "5bp2om1j0i32elmpbnu3bnp3gc",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ut7xriw7i5fxbp5o6vxxzglkse.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-i2isndl3ovhg7jtejtuqbuubma",
    "aws_cloud_logic_custom": [
        {
            "name": "UsersApi",
            "endpoint": "https://xqov61eb3b.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        },
        {
            "name": "helloApi",
            "endpoint": "https://rz7vmbefpf.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_mobile_analytics_app_id": "54faa78d5aa647f4949cf6c452a1ae63",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "users-dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
